### ISSUE TITLE
Show current directory size in /arc

### ISSUE THREAD

**Issue by brianmajor** [opencadc/science-platform#390] opened 2022-10-12 22:00 UTC
Show the current size of directories in the /arc file system.  Currently this is only available in /vault.  This is needed so that users know how close they are to their quotas.

**Comment by at88mph** [comment] 2024-11-26 22:51
If the issue is quota notification, the current quota is displayed in the UI:
![Screenshot from 2024-11-26 14-51-01](https://github.com/user-attachments/assets/89ecef9a-9e59-42cf-9270-e267389a41d5)

**Comment by at88mph** [comment] 2024-11-26 22:52
Closing for now, but reopen if still needed.

**Closed as not planned by at88mph** 2024-11-26 22:52 UTC
Labels: enhancement, wontfix
